# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
